# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      vendor:
        description: 'Vendor'
        default: ''
        required: true
        type: string
      product:
        description: 'Product'
        default: ''
        required: true
        type: string
      version:
        description: 'Version'
        default: ''
        required: true
        type: string
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Setup:
    runs-on: ubuntu-latest  

    steps:
    - name: Set repo_name
      run: echo repo_name=${GITHUB_REPOSITORY#*\/} >> $GITHUB_ENV
    - name: Reveiw out
      run: |
        echo ${{ env.repo_name }}
        echo ${{ github.event.inputs.vendor }} 
        echo ${{ github.event.inputs.product }}
        echo ${{ github.event.inputs.version }}
        echo "${{ github.event.inputs.version }}_"
