# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Vendor:
        description: 'Vendor'
        default: ''
        required: true
        type: string
      Product:
        description: 'Product'
        default: ''
        required: true
        type: string
      Version:
        description: 'Version'
        default: ''
        required: true
        type: string
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest  
    env:
      reponame: ${GITHUB_REPOSITORY#*\/}
      # "${{ github.repository }}" 
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo $reponame 
        echo $Vendor 
        echo $Product 
        echo $Version 
        echo "${{ github.repository }}"
        echo "${{ github.repository_owner }}"
        echo ${GITHUB_REPOSITORY#*\/}
        echo "${GITHUB_REPOSITORY_OWNER}"
        echo "${{ Vendor }}"

